name: AIP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Example (JS)
        run: |
          node examples/implementation.js

# --- Optional: Enable when ready ---
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '16'
#       - name: Install eslint
#         run: npm install eslint
#       - name: Run eslint
#         run: npx eslint examples/implementation.js

#   test-python:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.9'
#       - name: Install pytest
#         run: pip install pytest
#       - name: Run Python example
#         run: python examples/implementation.py

#   markdown-lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Install markdownlint
#         run: npm install markdownlint-cli
#       - name: Lint Markdown
#         run: npx markdownlint "**/*.md" --ignore node_modules
``
